config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  get 'howto', to: 'static_pages#howto'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
  end
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorites, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end
  get "search_tag", to: "posts#search_tag"

  resources :bookmarks, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post '/guest_login', to: 'user_sessions#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post

  has_many :favorites, dependent: :destroy

  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, presence: true, length: { maximum: 255 }
  validates :introduction, presence: false, length: { maximum: 500 }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  def own?(object)
    id == object.user_id
  end

  def bookmark(post)
    bookmark_posts << post
  end

  def unbookmark(post)
    bookmark_posts.destroy(post)
  end

  def bookmark?(post)
    bookmark_posts.include?(post)
  end

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.order(created_at: :desc).page(params[:page])
    @question_posts = @user.posts.where(post_status: '質問動画').order(created_at: :desc).page(params[:page])
    @q = current_user.bookmark_posts.ransack(params[:q])
    @bookmark_posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, success: t('defaults.message.profile_updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.profile_not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :password, :password_confirmation, :avatar, :avatar_cache)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookmark_posts.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_posts.present? %>
          <%= render @bookmark_posts %>
        <% else %>
          <div class="mb-3"><%= t('posts.index.no_result') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class="table">
  <% users.each do |user| %>
    <div class="card mb-2">
      <div class="card-body">
        <div class='row'>
          <div class="col-md-1">
            <%= image_tag user.avatar.url, class: 'rounded-circle', size: '50x50' %>
          </div>
          <div class="col-md-3">
            <h5 class="text-left fw-bold pt-2"><%= user.name %></h5>
          </div>
          <div class="col-md-2 fw-bold col-sm-6">
            <p class="text-center pt-2"><%= t('relationships.follow') %> : <%= user.followings.count %></p>
          </div>
          <div class="col-md-2 fw-bold col-sm-6">
            <p class="text-center pt-2"><%= t('relationships.follower') %> : <%= user.followers.count %></p>
          </div>
          <div class="col-md-2 col-sm-6">
            <p class="text-center"><%= render "relationships/follow_btn", user: user, options: { class: "" } %></p>
          </div>
          <div class="col-md-2 col-sm-6">
            <p class="text-center"><%= link_to t('users.show.title'), user_path(user), class: 'btn btn-primary rounded-pill' %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</table>

app/views/users/_question_posts.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @question_posts.present? %>
          <%= render @question_posts %>
        <% else %>
          <div class="mb-3"><%= t('posts.index.no_result') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_posts.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @user_posts.present? %>
          <%= render @user_posts %>
        <% else %>
          <div class="mb-3"><%= t('posts.index.no_result') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user, url: user_path, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
          <div class="form-group mb-3">
            <div class='mt-3 mb-3'>
              <%= image_tag @user.avatar.url, id: 'preview', size: '100x100', class: 'rounded-circle' %>
            </div>
            <%= f.label :avatar, placeholder: "image" %>
            <%= f.file_field :avatar, class: "form-control", accept: 'image/*', onchange: 'previewImage()' %>
            <%= f.hidden_field :avatar_cache %>
          </div>
          <div class="form-group mb-3">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group mb-3">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: 'form-control', rows: 10 %>
          </div>
          <%= f.submit  class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag "preview.js" %>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class='top-wrapper'>
  <div class='container'>
    <div class="row justify-content-center pt-5">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title text-center"><%= t('.title') %></h3>
          </div>
          <div class="card-body">
            <%= form_with model: @user do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
              <div class='form-group mb-2'>
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class='form-group mb-2'>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
              </div>
              <div class='form-group mb-2'>
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class='form-group mb-2'>
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
              <%= f.submit t('helpers.submit.create'), class: 'btn btn-primary mb-2' %>
            <% end %>
            <div class='text-center'>
              <%= link_to t('.to_login_page'), login_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-md-2 text-center mb-2">
      <%= image_tag @user.avatar.url, class: 'rounded-circle', size: '150x150' %>
    </div>
    <div class="col-md-10 mb-2">
      <div class="row">
        <div class="col-md-7 mb-2">
          <h3 class="text-left fw-bold pt-2"><%= @user.name %></h3>
        </div>
        <div class="col-md-5">
          <div class="row">
            <div class="col-sm-4">
              <p class="text-center fw-semibold">
                <%= link_to user_followings_path(@user), class: 'btn btn-outline-secondary rounded-pill' do %>
                  <%= t('header.follow') %> : <%= @user.followings.count %>
                <% end %>
              </p>
            </div>
            <div class="col-sm-4">
              <p class="text-center fw-semibold">
                <%= link_to user_followers_path(@user), class: 'btn btn-outline-secondary rounded-pill' do %>
                  <%= t('header.follower') %> : <%= @user.followers.count %>
                <% end %>
              </p>
            </div>
            <div class="text-center col-sm-4">
              <% if current_user == @user %>
                <%= link_to t('defaults.edit'), edit_user_path, class: 'btn btn-primary rounded-pill' %>
              <% else %>
                <%= render "relationships/follow_btn", user: @user, options: { class: ""} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <% if current_user == @user %>
            <%= User.human_attribute_name(:email) %> :
            <%= current_user.email %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <p><%= simple_format(@user.introduction) %></p>
      </div>
    </div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="post-tab" data-bs-toggle="tab" data-bs-target="#post-tab-pane" type="button" role="tab" aria-controls="post-tab-pane" aria-selected="true"><%= t('.post') %></button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="post_question-tab" data-bs-toggle="tab" data-bs-target="#post_question-tab-pane" type="button" role="tab" aria-controls="post_question-tab-pane" aria-selected="false"><%= t('.post_question') %></button>
      </li>
      <% if current_user == @user %>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="post_comment-tab" data-bs-toggle="tab" data-bs-target="#post_comment-tab-pane" type="button" role="tab" aria-controls="post_comment-tab-pane" aria-selected="false"><%= t('header.bookmark_index') %></button>
        </li>
      <% end %>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="post-tab-pane" role="tabpanel" aria-labelledby="post-tab" tabindex="0"><%= render 'user_posts' %></div>
      <div class="tab-pane fade" id="post_question-tab-pane" role="tabpanel" aria-labelledby="post_question-tab" tabindex="0"><%= render 'question_posts' %></div>
      <% if current_user == @user %>
        <div class="tab-pane fade" id="post_comment-tab-pane" role="tabpanel" aria-labelledby="post_comment-tab" tabindex="0"><%= render 'bookmark_posts' %></div>
      <% end %>
    </div>
  </div>
</div>