config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  get 'howto', to: 'static_pages#howto'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
  end
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorites, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end
  get "search_tag", to: "posts#search_tag"

  resources :bookmarks, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post '/guest_login', to: 'user_sessions#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="bi bi-youtube"></i>
      FPS Community
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class="nav-item">
          <%= link_to howto_path, class: 'nav-link' do %>
            <i class="bi bi-question-circle"></i><%= t('header.how_to') %>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to t('header.gest_login'), '/guest_login', class: 'nav-link', method: :post %>
        </li>

        <li class="nav-item">
          <%= link_to login_path, class: 'nav-link' do %>
            <i class="bi bi-box-arrow-in-right"></i><%= t('header.login') %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>">
		<%= message %>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12 col-12'>
        <div class='copyright'>
          <p class="text-center">Copyright ©︎ 2024 FPS_Community All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <i class="bi bi-youtube"></i>
      FPS Community
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item'>
          <%= link_to posts_path, class: 'dropdown-item' do %>
            <i class="bi bi-file-earmark-play"></i><%= t('header.post_index') %>
          <% end %>
        </li>

        <li class='nav-item'>
          <%= link_to new_post_path, class: 'dropdown-item' do %>
            <i class="bi bi-camera-reels"></i><%= t('header.create_post') %>
          <% end %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: {bs_toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'}, id: 'header-profile' do %>
            <%= image_tag current_user.avatar_url, class: 'rounded-circle mr15', width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'><%= current_user.name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to user_path(current_user), class: 'dropdown-item' do %>
              <i class="bi bi-person-square"></i><%= t('header.profile') %>
            <% end %>
            <%= link_to '#', class: 'dropdown-item' do %>
              <i class="bi bi-film"></i><%= t('header.posted_index') %>
            <% end %>
            <%= link_to bookmarks_posts_path, class: 'dropdown-item' do %>
              <i class="bi bi-bookmark-star"></i><%= t('header.bookmark_index') %>
            <% end %>
            <%= link_to "/users/#{current_user.id}/followings", class: 'dropdown-item' do %>
              <i class="bi bi-person-check-fill"></i><%= t('header.follow') %>
            <% end %>
            <%= link_to "/users/#{current_user.id}/followers", class: 'dropdown-item' do %>
              <i class="bi bi-people"></i><%= t('header.follower') %>
            <% end %>
            <%= link_to logout_path, class: 'dropdown-item', method: :delete do %>
              <i class="bi bi-box-arrow-right"></i><%= t('header.logout') %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>