config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  get 'howto', to: 'static_pages#howto'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
  end
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorites, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end
  get "search_tag", to: "posts#search_tag"

  resources :bookmarks, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post '/guest_login', to: 'user_sessions#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :movie, MovieUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy

  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  def save_tags(add_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - add_tags
    new_tags = add_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name: new_name)
      self.tags << tag
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:tag_names].split(',')
    if @post.save
      @post.save_tags(tag_list)
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Post.model_name.human)
      @tag_list = tag_list.join(',')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @tag_list = @post.tags.pluck(:name).join(',')
    @post_tags = @post.tags
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = current_user.posts.find(params[:id])
    tag_list = params[:post][:tag_names].split(',')
    if @post.update(post_params)
      @post.save_tags(tag_list)
      redirect_to @post, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Post.model_name.human)
      @tag_list = tag_list.join(',')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, status: :see_other, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  def search_tag
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @posts = @tag.posts.page(params[:page]).per(10)
  end

  def search
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def bookmarks
    @q = current_user.bookmark_posts.ransack(params[:q])
    @bookmark_posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def find_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :post_status, :movie, :movie_cache, name: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bookmark.html.erb
<%= link_to bookmarks_path(post_id: post.id), id: "bookmark-button-for-post-#{post.id}", class:"float-right", data: { turbo_method: :post } do %>
  <i class="bi bi-star"></i>
<% end %>

app/views/posts/_bookmark_button.html.erb
<% if current_user.bookmark?(post) %>
  <%= render 'posts/unbookmark', { post: post } %>
<% else %>
  <%= render 'posts/bookmark', { post: post } %>
<% end %>

app/views/posts/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline'>
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
      <i class="bi bi-pencil-fill"></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), id: "button-delete-#{post.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <i class="bi bi-trash-fill"></i>
    <% end %>
  </li>
</ul>

app/views/posts/_favorite.html.erb
<%= link_to post_favorites_path(post), class:"userList", data: { turbo_method: :delete } do %>
  <i class="bi bi-suit-heart-fill" aria-hidden="true" style="color: red;"></i>
  <span class='fw-bold'><%= post.favorites.count %></span>
<% end %>

app/views/posts/_favorite_btn.html.erb
<% if post.favorited_by?(current_user) %>
  <%= render 'posts/favorite', { post: post } %>
<% else %>
  <%= render 'posts/unfavorite', { post: post } %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= video_tag post.movie.url, id: 'preview', size: '300x200', controls: true, autobuffer: true %>
  <div class="form-group">
    <%= f.label :movie, placeholder: "video"  %>
    <%= f.file_field :movie, id: :post_movie, class: 'form-control mb-3', accept: 'video/*', onchange: 'previewImage()' %>
    <%= f.hidden_field :movie_cache %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control mb-3' %>
  </div>
  <div class="form-group mb-3">
    <%= f.radio_button :post_status, "質問動画" %>
    <%= f.label :question, t('posts.new.question') %>
    <%= f.radio_button :post_status, "" %>
    <%= f.label :not_question, t('posts.new.not_question') %>
  </div>
  <div class="form-group">
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names, value: @tag_list, class: 'form-control mb-3', placeholder: ",で区切って入力してください" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control mb-3', rows: 10 %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= javascript_include_tag "preview.js" %>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
	<div id="post-id-<%= post.id %>">
		<div class="card">
			<%= video_tag post.movie.url, class: 'card-img-top', size: '300*200', controls: true, autobuffer: true %>
			<div class="card-body">
				<div id="favorite-button-for-post-<%= post.id %>">
					<%= render "posts/favorite_btn", post: post %>
				</div>
				<% if post.post_status == "質問動画" %>
					<div class="badge bg-success text-wrap fs-6 mb-2">
						<%= post.post_status %>
					</div>
				<% end %>
				<div class="d-flex">
					<h4 class="card-title">
						<%= link_to truncate(post.title, length: 10), post_path(post) %>
					</h4>
					<div class="ms-auto">
						<% if current_user.own?(post) %>
							<%= render 'posts/crud_menus', post: post %>
						<% else %>
							<%= render 'posts/bookmark_button', post: post %>
						<% end %>
					</div>
				</div>
				<% post.tags.each do |tag| %>
					<span class="badge rounded-pill bg-primary text-decoration-none text-white mb-2">
						<%= tag.name %>
					</span>
				<% end %>
				<ul class="list-inline">
					<li><i class="bi bi-person"></i><%= link_to post.user.name, user_path(post.user) %></li>
					<li><i class="bi bi-calendar"></i><%= l post.created_at, format: :short %></li>
				</ul>
				<p class="card-text"><%= truncate(post.body, length: 30) %></p>
			</div>
		</div>
	</div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="d-flex mb-3">
    <%= f.search_field :title_or_body_cont, class: 'form-control me-2', placeholder: t('defaults.search_word'), id: 'search_field_of_post' %>
    <%= f.search_field :tags_name_cont, class: 'form-control me-2', placeholder: t('defaults.search_tag'), id: 'search_field_of_tag' %>
    <%= f.select :post_status_eq, [['質問動画', '質問動画']], {include_blank: '選択なし'}, class: 'sample border rounded me-2' %>
    <div class="input-group-append">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/posts/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(post_id: post.id)), id: "unbookmark-button-for-post-#{post.id}", class:"float-right", data: { turbo_method: :delete } do %>
  <i class="bi bi-star-fill"></i>
<% end %>

app/views/posts/_unfavorite.html.erb
<%= link_to post_favorites_path(post), class:"userList", data: { turbo_method: :post } do %>
  <i class="bi bi-suit-heart-fill" aria-hidden="true"></i>
  <span class='fw-bold'><%= post.favorites.count %></span>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, @post.title) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <%= render 'search_form', url: posts_path, q: @q %>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <div class="mb-3"><%= t('.no_result') %></div>
        <% end %>
      </div>
    </div>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-12'>
              <%= video_tag @post.movie.url, class: 'product-img', controls: true, autobuffer: true %>
            </div>
            <div class='col-md-12'>
              <% if @post.post_status == "質問動画" %>
                <div class="badge bg-success text-wrap fs-5 mb-2">
                  <%= @post.post_status %>
                </div>
              <% end %>
              <% if @post.favorited_by?(current_user) %>
                <%= link_to post_favorites_path(@post), class:"userList", method: :delete do %>
                  <i class="bi bi-suit-heart-fill" aria-hidden="true" style="color: red;"></i>
                  <span class='fw-bold'><%= @post.favorites.count %></span>
                <% end %>
              <% else %>
                <%= link_to post_favorites_path(@post), class:"userList", method: :post do %>
                  <i class="bi bi-suit-heart-fill" aria-hidden="true"></i>
                  <span class='fw-bold'><%= @post.favorites.count %></span>
                <% end %>
              <% end %>
              <div class='d-flex'>
                <h3 style='display: inline;'><%= @post.title %></h3>
                <div class="ms-auto">
                  <%= render 'crud_menus', post: @post if current_user.own?(@post) %>
                </div>
              </div>
              <% @post_tags.each do |tag| %>
                <span class="badge rounded-pill bg-primary text-decoration-none text-white mb-2">
                  <%= tag.name %>
                </span>
              <% end %>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @post.user.name %></li>
                <li class="list-inline-item"><%= l @post.created_at, format: :long %></li>
              </ul>
            </div>
          </div>
          <p><%= simple_format(@post.body) %></p>
        </div>
      </article>
    </div>
  </div>

  <!-- コメントフォーム -->
  <%= render 'comments/form', { post: @post, comment: @comment } %>  

  <!-- コメントエリア -->
  <%= render 'comments/comments', { comments: @comments } %>
</div>