config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  get 'howto', to: 'static_pages#howto'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
  end
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    resource :favorites, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end
  get "search_tag", to: "posts#search_tag"

  resources :bookmarks, only: %i[create destroy]
  resources :password_resets, only: %i[new create edit update]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post '/guest_login', to: 'user_sessions#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to posts_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def guest_login
    @guest_user = User.create(
    name: 'ゲスト',
    email: SecureRandom.alphanumeric(10) + "@email.com",
    password: 'password',
    password_confirmation: 'password'
    )
    auto_login(@guest_user)
    redirect_to root_path, success: 'ゲストとしてログインしました'
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class='top-wrapper'>
  <div class='container'>
    <div class="row justify-content-center pt-5">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title text-center"><%= t('.title') %></h3>
          </div>
          <div class="card-body">
            <%= form_with url: login_path, local: true do |f| %>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class="actions">
                <%= f.submit t('.login'), class: 'btn btn-primary' %>
              </div>
            <% end %>
            <div class='text-center'>
              <%= link_to t('.to_register_page'), new_user_path %>
              <%= link_to t('.password_forget'), '#' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>